# site settings
title: Miguel Ruiz
subtitle: Skateboard Instructor
email: miguelruizskates@gmail.com
description: Get skateboard lessons from a pro
baseurl: "" # the subpath of your site, e.g. /blog
url: https://miguelskates.com # the base hostname & protocol for your site
author:
address_name: Cerritos Skate Park
street_address: 19900 Bloomfield Avenue
city: Cerritos
state: CA
zip_code: 90703
country:
address_link: https://goo.gl/maps/M1bYj5Gkbt6M6vMCA
phone:
hours: "Mon – Fri: 6pm-7pm"
hours2: "Sat & Sun: Open"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/miguelruizskates/
venmo: Miguel-Ruiz-129
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
